"""Empirical analysis of the degree of independence between subproblems generated by
different decomposition strategies.

For a pair of features (i, j) and a base context S (a binary mask over the remaining
features), the second-order interaction (epistasis) under the wrapper fitness f is

    delta_ij(S) = [f(S + i + j) - f(S + j)] - [f(S + i) - f(S)]

If the contributions of i and j were additive (separable), delta_ij(S) = 0. The
Interaction Concentration Ratio of a decomposition is

    ICR = mean|delta|_intra / (mean|delta|_intra + mean|delta|_inter)

ICR ~ 0.5 means the partition captures no interaction structure; ICR -> 1 means
interactions are concentrated inside subcomponents, i.e. the subproblems are close to
independent of one another.
"""

import logging
import os
import sys
import time
from pathlib import Path

import numpy as np
from sklearn.metrics import balanced_accuracy_score
from sklearn.neighbors import KNeighborsClassifier

logging.disable(logging.CRITICAL)

# PyCCEA is expected to be pip-installed; for a source checkout, point PYCCEA_SOURCE at
# the directory containing the pyccea package. Decomposition results (per-run partitions)
# default to the local path and can be overridden with DECOMPOSITION_RESULTS_DIR.
_source = os.environ.get("PYCCEA_SOURCE")
if _source:
    sys.path.insert(0, _source)
RESULTS = Path(os.environ.get(
    "DECOMPOSITION_RESULTS_DIR",
    r"c:\Users\pedbr\OneDrive\Education\Doctor's degree\Research\Papers"
    r"\Decomposition\Results\decomposition",
))

from pyccea.utils.config import load_params  # noqa: E402
from pyccea.utils.datasets import DataLoader  # noqa: E402

# 1-nearest-neighbour, matching ClassificationModel in pyccea/utils/models.py
KNN_KWARGS = {"n_neighbors": 1}


def load_dataset(name):
    """Load and preprocess a dataset using the same configuration as the experiments."""
    conf = load_params(str(SOURCE / "pyccea" / "parameters" / "dataloader.toml"))
    data = DataLoader(dataset=name, conf=conf)
    data.get_ready()
    return data


class FoldCache:
    """Pre-compute the normalized k folds once and evaluate feature masks against them.

    'WrapperEvaluation.evaluate' calls 'DataLoader.get_fold', which re-runs winsorization
    and min-max normalization over the full feature matrix on every call. That work is
    identical for every mask, so it is hoisted out of the loop here. The per-fold model
    fitting and scoring are unchanged, which 'validate' checks explicitly.
    """

    def __init__(self, data):
        self.folds = [data.get_fold(k) for k in range(data.kfolds)]
        self.kfolds = data.kfolds
        self.n_features = data.X_train.shape[1]

    def evaluate(self, mask):
        """Mean balanced accuracy over the k folds for a boolean feature mask."""
        if not mask.any():
            return 0.0
        total = 0.0
        for X_train, y_train, X_val, y_val in self.folds:
            model = KNeighborsClassifier(**KNN_KWARGS)
            model.fit(X_train[:, mask], y_train)
            total += balanced_accuracy_score(y_val, model.predict(X_val[:, mask]))
        return total / self.kfolds

    def permute(self, order):
        """Return a new cache whose feature columns follow 'order'."""
        clone = object.__new__(FoldCache)
        clone.folds = [
            (X_train[:, order], y_train, X_val[:, order], y_val)
            for X_train, y_train, X_val, y_val in self.folds
        ]
        clone.kfolds = self.kfolds
        clone.n_features = len(order)
        return clone


def validate(data, cache, n_masks=15, seed=0):
    """Check the fold cache reproduces WrapperEvaluation on random masks."""
    from pyccea.evaluation.wrapper import WrapperEvaluation

    reference = WrapperEvaluation(
        task="classification",
        model_type="k_nearest_neighbors",
        eval_function="balanced_accuracy",
        eval_mode="k_fold",
        n_classes=len(np.unique(data.y_train)),
        store_estimators=False,
        cache_size=0,
        use_subprocess=False,
    )
    rng = np.random.default_rng(seed)
    worst = 0.0
    for _ in range(n_masks):
        solution = (rng.random(cache.n_features) < 0.5).astype(int)
        expected = reference.evaluate(solution, data)["balanced_accuracy"]
        actual = cache.evaluate(solution.astype(bool))
        # The reference rounds to 4 decimals; the cache keeps full precision.
        worst = max(worst, abs(expected - round(actual, 4)))
    return worst


def as_int_array(value):
    """Coerce a stored index sequence to an integer array.

    Some result files keep these columns as lists, others as the string repr of a numpy
    array (e.g. '[19 72 12\n 73 ...]'), so both forms have to be handled.
    """
    if isinstance(value, str):
        body = value.strip().lstrip("[").rstrip("]")
        # 'feature_idxs' is stored space-separated, 'subcomp_sizes' comma-separated.
        separator = "," if "," in body else " "
        return np.fromstring(body, sep=separator, dtype=int)
    return np.asarray(value, dtype=int)


def subcomponent_labels(row, n_original):
    """Map each column of the strategy's own feature space to its subcomponent.

    'removed_features' indexes the original feature space and is applied first, so the
    surviving columns keep their relative order. 'feature_idxs' is then a permutation of
    the post-removal space, and 'subcomp_sizes' slices it sequentially.

    Returns the permutation to apply to the post-removal matrix and the subcomponent
    label of each resulting column.
    """
    removed = row.get("removed_features")
    removed = np.asarray([], dtype=int) if removed is None else as_int_array(removed)
    kept = np.setdiff1d(np.arange(n_original), removed)

    order = as_int_array(row["feature_idxs"])
    sizes = as_int_array(row["subcomp_sizes"])
    if sizes.sum() != order.size:
        raise ValueError(f"subcomp_sizes sum {sizes.sum()} != len(feature_idxs) {order.size}")

    labels = np.repeat(np.arange(sizes.size), sizes)
    return kept, order, labels


def sample_pairs(labels, n_intra, n_inter, rng):
    """Sample within-subcomponent and between-subcomponent feature pairs."""
    groups = [np.where(labels == c)[0] for c in np.unique(labels)]
    eligible = [g for g in groups if g.size >= 2]

    intra = []
    if eligible:
        # Weight each subcomponent by how many within pairs it contains.
        weights = np.array([g.size * (g.size - 1) / 2 for g in eligible], dtype=float)
        weights /= weights.sum()
        for _ in range(n_intra):
            g = eligible[rng.choice(len(eligible), p=weights)]
            intra.append(tuple(rng.choice(g, size=2, replace=False)))

    inter = []
    if len(groups) >= 2:
        for _ in range(n_inter):
            a, b = rng.choice(len(groups), size=2, replace=False)
            inter.append((rng.choice(groups[a]), rng.choice(groups[b])))

    return intra, inter


def deltas(cache, pairs, n_contexts, rng, density=0.5):
    """Second-order interaction magnitudes for a list of feature pairs."""
    out = []
    for i, j in pairs:
        for _ in range(n_contexts):
            base = rng.random(cache.n_features) < density
            base[i] = False
            base[j] = False

            f_00 = cache.evaluate(base)
            with_i = base.copy()
            with_i[i] = True
            f_10 = cache.evaluate(with_i)
            with_j = base.copy()
            with_j[j] = True
            f_01 = cache.evaluate(with_j)
            both = with_i
            both[j] = True
            f_11 = cache.evaluate(both)

            out.append((f_11 - f_01) - (f_10 - f_00))
    return np.asarray(out)


def icr(intra, inter):
    """Interaction concentration ratio."""
    a, b = np.abs(intra).mean(), np.abs(inter).mean()
    return np.nan if (a + b) == 0 else a / (a + b)


def permutation_null(delta_intra, delta_inter, n_perm=2000, seed=0):
    """Null distribution of ICR when the partition carries no information.

    Pools the observed |delta| values and reassigns the intra/inter labels at random,
    keeping the group sizes fixed. Returns the null ICRs and the one-sided p-value for
    the observed ICR.
    """
    rng = np.random.default_rng(seed)
    pool = np.abs(np.concatenate([delta_intra, delta_inter]))
    n_intra = delta_intra.size
    observed = icr(delta_intra, delta_inter)

    null = np.empty(n_perm)
    for p in range(n_perm):
        shuffled = rng.permutation(pool)
        a, b = shuffled[:n_intra].mean(), shuffled[n_intra:].mean()
        null[p] = np.nan if (a + b) == 0 else a / (a + b)
    return observed, null, (null >= observed).mean()


STRATEGY_FILES = {
    "PSTD": "self_tuning_proposed_with_feature_idxs.parquet",
    "SymmetricUncertainty": "symmetric_uncertainty_with_feature_idxs.parquet",
    "Sequential": "sequential.parquet",
    "Random": "random.parquet",
    "Clustering": "clustering.parquet",
}


def run(dataset, strategies, n_runs, n_intra, n_inter, n_contexts, seed=0):
    """Measure ICR for each strategy on one dataset."""
    import pandas as pd

    data = load_dataset(dataset)
    base = FoldCache(data)
    n_original = data.X_train.shape[1]
    print(f"{dataset}: X_train={data.X_train.shape} kfolds={data.kfolds}")

    rows = []
    for name in strategies:
        table = pd.read_parquet(RESULTS / STRATEGY_FILES[name])
        subset = table[table.dataset == dataset]
        if subset.empty:
            print(f"  {name}: no runs for this dataset, skipping")
            continue

        for run_id in sorted(subset.run.unique())[:n_runs]:
            row = subset[subset.run == run_id].iloc[0]
            kept, order, labels = subcomponent_labels(row, n_original)
            cache = base.permute(kept[order])

            rng = np.random.default_rng(seed + int(run_id))
            intra_pairs, inter_pairs = sample_pairs(labels, n_intra, n_inter, rng)

            t0 = time.time()
            d_intra = deltas(cache, intra_pairs, n_contexts, rng)
            d_inter = deltas(cache, inter_pairs, n_contexts, rng)
            observed, null, pvalue = permutation_null(d_intra, d_inter)

            rows.append({
                "dataset": dataset,
                "strategy": name,
                "run": run_id,
                "n_subcomps": len(np.unique(labels)),
                "n_features": cache.n_features,
                "mean_abs_intra": np.abs(d_intra).mean(),
                "mean_abs_inter": np.abs(d_inter).mean(),
                "frac_zero": float((np.concatenate([d_intra, d_inter]) == 0).mean()),
                "icr": observed,
                "icr_null_mean": np.nanmean(null),
                "icr_null_sd": np.nanstd(null),
                "p_value": pvalue,
                "seconds": time.time() - t0,
            })
            print(f"  {name} run={run_id}: ICR={observed:.4f} "
                  f"null={np.nanmean(null):.4f}+-{np.nanstd(null):.4f} "
                  f"p={pvalue:.4f} |d|intra={np.abs(d_intra).mean():.5f} "
                  f"|d|inter={np.abs(d_inter).mean():.5f} "
                  f"zeros={float((np.concatenate([d_intra, d_inter]) == 0).mean()):.2f} "
                  f"({time.time() - t0:.0f}s)")
    return pd.DataFrame(rows)


if __name__ == "__main__":
    dataset = sys.argv[1] if len(sys.argv) > 1 else "libras"

    t0 = time.time()
    data = load_dataset(dataset)
    cache = FoldCache(data)
    print(f"{dataset}: X_train={data.X_train.shape} kfolds={data.kfolds} "
          f"load={time.time() - t0:.1f}s")

    t0 = time.time()
    worst = validate(data, cache)
    print(f"validation: max |reference - cache| = {worst:.2e}  ({time.time() - t0:.1f}s)")

    rng = np.random.default_rng(0)
    t0 = time.time()
    for _ in range(20):
        cache.evaluate(rng.random(cache.n_features) < 0.5)
    print(f"cached sec/eval = {(time.time() - t0) / 20:.4f}")
